version: '2'
services:
    api:
        build: .
        container_name: computacao_ufcg-api
        command: python3 app.py
        environment:
            - PYTHONPATH=/var/app/api/
        volumes:
            - ./api/:/var/app/api/
        ports:
            - 8000:8000
